-- DipScore 초기 마이그레이션
-- 비즈니스 스키마는 아직 없음. TimescaleDB 확장 활성화만 수행한다.
-- (timescale/timescaledb 이미지는 template DB 에 확장을 미리 로드하지만,
--  다른 PostgreSQL 이미지로 교체하는 경우를 대비해 멱등하게 선언해 둔다.)

CREATE EXTENSION IF NOT EXISTS timescaledb;

-- 스모크 테스트용 임시 테이블 (다음 마이그레이션에서 제거 예정)
CREATE TABLE IF NOT EXISTS app_bootstrap (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note        TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
